### ISSUE TITLE
Importar funções

### ISSUE THREAD

**Issue by gabhirayama** [atp/enem#9]
@ewout , estou tentando importar as funções de util.py, mas sempre retorno o erro:

--> The R package "mirt" is not installed.

Pode me ajudar?

**Comment by ewout** [comment]
Ah sim, deve rodar as primeiras células de 04-IRT.ipynb e des-comentar utils.install_packages('mirt')
utils.install_packages('mirtCAT').

Acho que rodar 
```
import rpy2
from rpy2.robjects.packages import importr
utils = importr('utils')
utils.install_packages('mirt')
utils.install_packages('mirtCAT')
```
uma vez em qualquer notebook deve resolver também. Após disso, o mirt e mirtCAT estarão instalados para seu usuário.

**Comment by gabhirayama** [comment]
Perfeito! Funcionou!
